### ISSUE TITLE
weird error idk (thread "main" panicked)

### ISSUE THREAD

**Issue by Lightning-isnt-a-dev** [dromzeh/wuwa-fps-unlocker#1] opened 2024-05-25 11:21 UTC
![image](https://github.com/dromzeh/wuwa-fps-unlocker/assets/112514086/e9556b12-a3a9-4bac-aec5-2bd1657205d3)

**Comment by dromzeh** [comment] 2024-05-25 15:11
looking into this, thanks for reporting

**Comment by dromzeh** [comment] 2024-05-25 15:35
hey @Lightning-isnt-a-dev, i believe the fix in 8d3481a should work

can you please let me know if the issue is still occuring when trying the latest release?: https://github.com/dromzeh/wuwa-fps-unlocker/releases/tag/v0.0.3

**Comment by dromzeh** [comment] 2024-05-27 01:54
closing - plz write a comment on this issue if the error is persisting after trying the newest release

**Closed as completed by dromzeh** 2024-05-27 01:54 UTC
Labels: bug, question
